# Generated by Django 5.0.2 on 2024-09-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadReserva',
            fields=[
                ('estadoReservaId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('estadoReservaNombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('tipoSolicitudId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('tipoSolicitud', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('fechareserva', models.DateField()),
                ('horareserva', models.TimeField()),
                ('cantidadpersonas', models.IntegerField()),
                ('observaciones', models.CharField(max_length=5000)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('donante', models.BooleanField()),
                ('edad', models.IntegerField()),
                ('estadoReservaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='App.estadreserva')),
                ('tipoSolicitudId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='App.tiporeserva')),
            ],
        ),
    ]
